Task5WebApp/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Task5WebApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Task5WebApp/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.Security.Claims;
using Task5WebApp.Data;
using Task5WebApp.Model;

namespace Task5WebApp.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        
        private Task5WebAppContext _context;

        public IndexModel(ILogger<IndexModel> logger, Task5WebAppContext context)
        {
            _logger = logger;
            _context = context;
        }

        [BindProperty]
        [Required, MinLength(1)]
        public string Name { get; set; }
       
        [TempData]
        public string ErrorMessage { get; set; }

        public IActionResult OnGet()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToPage("message");
            }
            return Page();
        }

        public async Task<IActionResult> OnPostLoginAsync()
        {
            if (ModelState.IsValid)
            {
                string name = await GetOrCreate();
                await Authenticate(name);
            }
            return RedirectToPage("message");
        }

        public async Task<IActionResult> OnPostLogoutAsync()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToPage();
        }

        private async Task<string> GetOrCreate()
		{
            var AppUser = await _context.ApplicationUser.FirstOrDefaultAsync(u => u.Name == Name);
            if (AppUser == null)
            {
                AppUser = CreateUser();
                AppUser.Name = Name;
                await _context.ApplicationUser.AddAsync(AppUser);
                await _context.SaveChangesAsync();
            }
            return AppUser.Name;
        }

        private async Task Authenticate(string name)
		{
            var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.NameIdentifier, name),
                };
            ClaimsIdentity id = new ClaimsIdentity(claims, "ApplicationCookie", ClaimsIdentity.DefaultNameClaimType, ClaimsIdentity.DefaultRoleClaimType);
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(id));
        }

        private ApplicationUser CreateUser()
        {
            try
            {
                return Activator.CreateInstance<ApplicationUser>();
            }
            catch
            {
                throw new InvalidOperationException($"Can't create an instance of '{nameof(ApplicationUser)}'. " +
                    $"Ensure that '{nameof(ApplicationUser)}' is not an abstract class and has a parameterless constructor, or alternatively");
            }
        }
    }
}

Task5WebApp/Pages/Message.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Task5WebApp.Data;
using Task5WebApp.Model;


namespace Task5WebApp.Pages
{
    [Authorize]
    public class MessageModel : PageModel
    {
        private readonly Task5WebAppContext _context;

        public MessageModel(Task5WebAppContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Message Message { get; set; } = default!;

        public IList<Message> Messages { get; set; } = default!;

        public string CurrentUserName { get; set; } = default!;

        [TempData]
        public string Alert { get; set; }

        public async Task<IActionResult> OnPostSendAsync()
        {
            if (ModelState.IsValid)
            {
                SetUserName();
                if (CurrentUserName != null)
                {
                    if(await IfExistRecipient())
                    {
                        Message.Sender = CurrentUserName;
                        Message.TimeOfSending = DateTime.Now.ToString("dd-MM-yyyy HH:mm");
                        _context.Message.Add(Message);
                        await _context.SaveChangesAsync();
                        Alert = $"Message to {Message.Recipient} was sent";
                    }
                }
            }
            return RedirectToPage();
        }

        public async Task OnGetAsync()
        {
            SetUserName();
            if (_context.Message != null || CurrentUserName != null)
            {
                Messages = await _context.Message.Where(m => m.Recipient == CurrentUserName).OrderBy(m => m.TimeOfSending).ToListAsync();
            }
        }

        public async Task<IActionResult> OnPostLogoutAsync()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToPage();
        }

        public async Task<IActionResult> OnGetSearchAsync(string term)
        {
            var names = await _context.ApplicationUser.Where(u => u.Name.Contains(term)).Select(u => u.Name).ToListAsync();
            return new JsonResult(names);
        }


        public async Task<IActionResult> OnGetUpdateAsync()
        {
            SetUserName();
            Messages = await _context.Message.Where(m => m.Recipient == CurrentUserName).ToListAsync();
            return new JsonResult(Messages);
        }

        public async Task<IActionResult> OnGetIdAsync(int id)
        {
            Messages = await _context.Message.Where(m => m.Id == id).ToListAsync();
            return new JsonResult(Messages);
        }

        public void SetUserName()
        {
            ClaimsPrincipal currentUser = this.User;
            CurrentUserName = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;
        }

        public async Task<bool> IfExistRecipient()
        {
            var recipient = await _context.ApplicationUser.FirstOrDefaultAsync(u => u.Name == Message.Recipient);
            if(recipient != null)
            {
                return true;
            }
            return false;
        }
    }
}

Task5WebApp/Pages/Index.cshtml
@page
@model IndexModel

@{
	ViewData["Title"] = "Home page";
}

@section Scripts {
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

@if (!User.Identity.IsAuthenticated)
{
	<div class="text-center">
		<h1 class="display-4">Welcome</h1>
	</div>
	<div class="row justify-content-center">
		<div class="col-md-4">
			<form method="post" asp-page-handler="login">
				<span asp-validation-for="Name" class="text-danger"></span>
				<div class="form-floating">
					<input asp-for="Name" class="form-control" autocomplete="username" aria-required="true" />
					<label asp-for="Name" class="form-label"></label>
					<div>
						<button id="login-submit" type="submit" class="w-100 btn btn-lg btn-primary">Log in</button>
					</div>
				</div>
			</form>
		</div>
	</div>
}

Task5WebApp/Pages/Message.cshtml
@page
@model Task5WebApp.Pages.MessageModel

@{
	ViewData["Title"] = "Message";
}

@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
	<script>
		$(document).ready(function () {
			$('#nameOfRecipient').autocomplete({
				source: '@Url.Page("Message", "search")'
			});
		});
	</script>
	<script>
		$(document).ready(function () {
			var result = setInterval(ajaxCall, 5000);
		});

		function ajaxCall() {
			$.ajax({
				type: "GET",
				url: '@Url.Page("Message", "update")',
				data: "{}",
				contentType: "application/json; charset=utf-8",
				dataType: "json",
				success: function (result) {
					var numberOfMessages = $('#numberOfMessages').text();
					if (Object.keys(result).length > numberOfMessages) {
						for (var i = numberOfMessages; i < Object.keys(result).length; i++) {
							var $tr = $('<tr>').append(
								$('<td>').text(result[i].sender),
								$('<td>').text(result[i].timeOfSending),
								$('<td>').append('<button class="btn btn-link link-secondary" onclick="ajaxCallId('+result[i].id+')">'+result[i].title+'</button>')
							).appendTo('#tbody');
						}
						$('#numberOfMessages').text(Object.keys(result).length);
					}
				}
			});
		}

		function ajaxCallId(id) {
			$.ajax({
				type: "GET",
				url: '@Url.Page("Message", "id")',
				data: "id=" + id,
				contentType: "application/json; charset=utf-8",
				dataType: "json",
				success: function (result) {
					$('#staticBackdropLabel').text('Title: ' + result[0].title);
					$('.modal-body').text(result[0].body);
					const myModal = new bootstrap.Modal('#staticBackdrop');
					const modalEl = document.getElementById('staticBackdrop');
					myModal.show(modalEl);
				}
			});
		}

		$('.prevent').click(function (e) {
			e.preventDefault();
			ajaxCallId(this.id);
		})
	</script>
}
@if (Model.Alert != null)
{
	<div class="alert alert-success alert-dismissible fade show" role="alert">
		@Model.Alert
		<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
	</div>
}

<h1 class="text-center">Welcome @Model.CurrentUserName</h1>
<div class="row justify-content-center">
	<div class="col-md-4">
		<form method="post" asp-page-handler="send">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<div class="form-group">
				<label asp-for="Message.Recipient" class="control-label"></label>
				<input asp-for="Message.Recipient" class="form-control" id="nameOfRecipient" />
				<span asp-validation-for="Message.Recipient" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Message.Title" class="control-label"></label>
				<input asp-for="Message.Title" class="form-control" />
				<span asp-validation-for="Message.Title" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Message.Body" class="control-label">Message</label>
				<textarea asp-for="Message.Body" class="form-control"></textarea>
				<span asp-validation-for="Message.Body" class="text-danger"></span>
			</div>
			<div class="form-group text-center mt-2">
				<input type="submit" value="Send" class="btn btn-primary w-50" />
			</div>
		</form>
	</div>
</div>
<p hidden id="numberOfMessages">@Model.Messages.Count</p>
<div class="row justify-content-center mt-3">
	<div class="col-md-6 text-center">
		<table class="table">
			<thead>
				<tr>
					<th>Sender</th>
					<th>Date</th>
					<th>Title</th>
				</tr>
			</thead>
			<tbody id="tbody">
				@foreach (var item in Model.Messages)
				{
					<tr>
						<td>
							@Html.DisplayFor(modelItem => item.Sender)
						</td>
						<td>
							@Html.DisplayFor(modelItem => item.TimeOfSending)
						</td>
						<td>
							<button class="btn btn-link link-secondary" onclick="ajaxCallId(@item.Id)">@Html.DisplayFor(modelItem => item.Title)</button>
						</td>
					</tr>
				}
			</tbody>
		</table>
	</div>
</div>

<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="staticBackdropLabel"></h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
			</div>
		</div>
	</div>
</div>

Task5WebApp/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests"> 
	<title>@ViewData["Title"] - Task5WebApp</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/Task5WebApp.styles.css" asp-append-version="true" />
	<link rel="stylesheet" href="http://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
	<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
	<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container">
				<a class="navbar-brand" asp-area="" asp-page="/Index">Task5WebApp</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						@if (User.Identity.IsAuthenticated)
						{
							<li>
								<form method="post" asp-page-handler="logout">
									<button class="nav-link btn btn-link text-dark">Log out</button>
								</form>
							</li>
						}
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2022 - Task5WebApp - <a asp-area="" asp-page="/Privacy">Privacy</a>
		</div>
	</footer>

	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>

	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>